### ISSUE TITLE
Problem while parsing wat, if a map variable is defined

### ISSUE THREAD

**Issue by hugo-dc** [ewasm/biturbo#59]
If we define the following map:

```typescript
let myMap: new Map<i32, i32>()
```

And try to build the WebAssembly module (for example `npm run evm:build) we ge the following error:

```
[00:05:54] 'evm' errored after 5.36 s
[00:05:54] Error: parseWat failed:
evm_with_keccak.wat:379:25: error: unexpected char
 (func $~lib/map/Map<i32,i32>#clear (; 13 ;) (type $FUNCSIG$vi) (param $0 i32)
                        ^
evm_with_keccak.wat:379:26: error: unexpected token i32>#clear, expected ).
 (func $~lib/map/Map<i32,i32>#clear (; 13 ;) (type $FUNCSIG$vi) (param $0 i32)
                         ^^^^^^^^^^
evm_with_keccak.wat:379:63: error: unexpected token ), expected (.
 (func $~lib/map/Map<i32,i32>#clear (; 13 ;) (type $FUNCSIG$vi) (param $0 i32)
                                                              ^

    at Object.parseWat (/home/hugo/workspace/biturbo/node_modules/wabt/index.js:25:14653)
    at mergeWats (/home/hugo/workspace/biturbo/gulpfile.js:178:23)
    at buildEvm (/home/hugo/workspace/biturbo/gulpfile.js:49:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by s1na** [comment]
Sorry for the late response Hugo.

Casey had also faced this before and he added a workaround to the gulpfile which you can also use. Hopefully this issue should be fixed (maybe it already is) in wabt and we can avoid this hacky workaround.

https://github.com/ewasm/biturbo/blob/005b684528ebfc208a3578e47de2ea627bfdb178/gulpfile.js#L132-L137
